console.log("String Methods");
x = "Santosh Kumar";
console.log(x.charAt(6));
console.log(x.charCodeAt(6));
y = x.concat(" K");
console.log(y);
console.log(x.startsWith("San"));
console.log(x.endsWith("Kumar"));
console.log(y.includes("P"));
console.log(x.indexOf("a"));
console.log(x.lastIndexOf("a"));
z = "Anu ";
console.log(z.repeat(11));
z = "Cartoon";
console.log(z.replace("r","a"));
console.log(x.slice(1,5));
console.log(y.split(" "));
