console.log("Operators");
/*let a=5;
let b=3;
console.log(a+b);
console.log(a-b);
console.log(a*b);
console.log(a/b);
console.log(a**b);
var c=30;
console.log(c);
c= c+10;
console.log(c);
c+=5;
console.log(c);
var c=30;
console.log(c);
c= c-10;
console.log(c);
c-=5;
console.log(c);
var c=3;
console.log(c);
c= c*3;
console.log(c);
c*=5;
console.log(c);
var c=30;
console.log(c);
c= c/10;
console.log(c);
c/=5;
console.log(c);
var c=30;
console.log(c);
c= c%10;
console.log(c);
c%=5;
console.log(c);
*/
var a=10;
var b="10";
console.log(a==b);
console.log(a===b);
console.log(a!=b);
console.log(a!==b);
var c=10;
var d=20;
console.log(c>d);
console.log(c<d)
console.log(c>=d);
console.log(c<=d);
console.log("Logical Operators");
var age=10;
var voter=true;
console.log(age>=18);
console.log(voter==true);
console.log((age>=18) && (voter==true));
console.log((age>=18) || (voter==true));
console.log(!(age>=18));
var x=5;
console.log(+x);
var y=5;
console.log(-y);
var ages=12;
var res=(ages>=18)?'adult':"minor";
console.log(res);
var p1=100;
console.log(p1++);
console.log(p1);
var p2=100;
console.log(++p2);
var q1=200;
console.log(q1--);
var q2=200;
console.log(--q2);
var e="Hello"
var f=" Codegnan"
console.log(e+f);